server:
  port: 8080
spring:
  application:
    name: sprint-poker #指定服务名
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sprint_poker?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=true
    username: root
    password: 1234
  jpa:
    database: MySQL
    show-sql: true

jwt:
  config:
    key: asml  #密钥
    ttl: 315360000000 # 过期时间10 years
